# Generated by Django 3.2.16 on 2022-12-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutmusic',
            name='time_from',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cutmusic',
            name='time_to',
            field=models.FloatField(blank=True, default=30000, null=True),
        ),
    ]
