# Generated by Django 3.2.16 on 2022-12-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cut', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_music', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('second_music', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('mixed_music', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
