# Generated by Django 3.2.16 on 2022-12-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cut', '0002_auto_20221217_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumental', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('vocals', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('vocals_percent', models.IntegerField()),
                ('instrumental_percent', models.IntegerField()),
                ('joined_music', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
