# Generated by Django 3.2.16 on 2023-01-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cut', '0004_auto_20221226_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinmusic',
            name='first_music',
            field=models.CharField(max_length=255),
        ),
    ]
