# Generated by Django 3.2.16 on 2023-01-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cut', '0005_alter_joinmusic_first_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinmusic',
            name='first_music',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
