# Generated by Django 3.2.16 on 2022-12-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, verbose_name='users.User')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
        migrations.CreateModel(
            name='Minus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocals', models.CharField(max_length=250)),
                ('accompaniment', models.CharField(max_length=250)),
                ('song_name', models.CharField(blank=True, max_length=250, null=True)),
                ('singer_name', models.CharField(blank=True, max_length=250, null=True)),
                ('background', models.FileField(default='documents/2022/12/07/default.mp4', upload_to='documents/%Y/%m/%d')),
                ('user', models.CharField(max_length=250, verbose_name='users.User')),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('music_img', models.CharField(default='media/documents/2022/12/07/naushnik.jpg', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('moment', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-moment'],
            },
        ),
    ]
