# Generated by Django 3.2.16 on 2022-12-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minus',
            name='background',
            field=models.FileField(default='documents/green.mp4', upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='minus',
            name='music_img',
            field=models.CharField(default='media/documents/naushnik.jpg', max_length=255),
        ),
    ]
