# Generated by Django 3.2.16 on 2022-12-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minus',
            name='background',
            field=models.FileField(default='documents/2022/12/07/default.mp4', upload_to='documents/%Y/%m/%d'),
        ),
    ]
