# Generated by Django 3.2.16 on 2022-12-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20221212_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minus',
            name='music_img',
            field=models.TextField(default='media/documents/naushnik.jpg'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255, verbose_name=(('ZST', 'ЗАСТОЛЬНЫЕ ПЕСНИ'), ('90-E', '90-Е'), ('CHILD', 'дЕТСКИЕ ПЕСНИ')))),
                ('minus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.minus')),
            ],
        ),
    ]
