# Generated by Django 3.2.16 on 2022-12-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_minus_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='minus',
            name='music_img',
            field=models.TextField(default='media/documents/2022/12/07/naushnik.jpg'),
        ),
    ]
