# Generated by Django 3.2.16 on 2022-12-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20221217_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='genre',
            field=models.CharField(choices=[('ZST', 'ЗАСТОЛЬНЫЕ ПЕСНИ'), ('90-E', '90-Е'), ('CHILD', 'дЕТСКИЕ ПЕСНИ')], max_length=255),
        ),
    ]
