# Generated by Django 3.2.16 on 2022-12-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_category_minus'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(default=1, upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
