# Generated by Django 3.2.16 on 2023-01-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_samplebackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='minus',
            name='duration',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
